/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/cortex/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["cortex.agents.index"];
        put?: never;
        post: operations["cortex.agents.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cortex/agents/{agent}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["cortex.agents.show"];
        put?: never;
        post?: never;
        delete: operations["cortex.agents.destroy"];
        options?: never;
        head?: never;
        patch: operations["cortex.agents.update"];
        trace?: never;
    };
    "/cortex/agents/{agent}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cortex.agents.run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cortex/servers/{server}/instructions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["cortex.servers.instructions.show"];
        put?: never;
        post?: never;
        delete: operations["cortex.servers.instructions.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cortex/servers/{server}/instructions/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["cortex.servers.instructions.versions.index"];
        put?: never;
        post: operations["cortex.servers.instructions.versions.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cortex/servers/{server}/instructions/versions/{version}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cortex.servers.instructions.versions.publish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cortex/servers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["cortex.servers.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cortex/prompts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["cortex.prompts.index"];
        put?: never;
        post: operations["cortex.prompts.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cortex/prompts/{prompt}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["cortex.prompts.show"];
        put?: never;
        post?: never;
        delete: operations["cortex.prompts.destroy"];
        options?: never;
        head?: never;
        patch: operations["cortex.prompts.update"];
        trace?: never;
    };
    "/cortex/prompts/{prompt}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["cortex.prompts.versions.index"];
        put?: never;
        post: operations["cortex.prompts.versions.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cortex/prompts/{prompt}/versions/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["cortex.prompts.versions.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cortex/prompts/{prompt}/versions/{version}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cortex.prompts.versions.publish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cortex/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["cortex.providers.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cortex/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["cortex.tools.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cortex/tools/{tool}/description": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["cortex.tools.description.show"];
        put?: never;
        post?: never;
        delete: operations["cortex.tools.description.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cortex/tools/{tool}/description/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["cortex.tools.description.versions.index"];
        put?: never;
        post: operations["cortex.tools.description.versions.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cortex/tools/{tool}/description/versions/{version}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cortex.tools.description.versions.publish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentResource */
        AgentResource: {
            name: string;
            slug: string;
            description: string | null;
            provider: string | null;
            model: string | null;
            settings: {
                [key: string]: unknown;
            } | null;
            tools: string[];
            prompt?: string;
            prompt_version?: number;
            sub_agents?: unknown[];
            created_at: string | null;
            updated_at: string | null;
        };
        /** AgentRunResource */
        AgentRunResource: {
            text: string;
            usage: string;
        };
        /** McpInstructionResource */
        McpInstructionResource: {
            server: string;
            published_version: number;
            published_content: string;
            created_at: string | null;
            updated_at: string | null;
        };
        /** McpInstructionVersionResource */
        McpInstructionVersionResource: {
            version: number;
            content: string;
            created_at: string | null;
        };
        /** McpServerResource */
        McpServerResource: {
            name: string;
            instructions: string;
        };
        /** PromptResource */
        PromptResource: {
            name: string;
            slug: string;
            description: string | null;
            published_version?: components["schemas"]["PromptVersionResource"];
            created_at: string | null;
            updated_at: string | null;
        };
        /** PromptVersionResource */
        PromptVersionResource: {
            version: number;
            content: string;
            created_at: string | null;
        };
        /** RunAgentRequest */
        RunAgentRequest: {
            input: string;
        };
        /** StoreAgentRequest */
        StoreAgentRequest: {
            name: string;
            slug: string;
            description?: string | null;
            provider?: string | null;
            model?: string | null;
            settings?: {
                temperature: number;
                max_steps: number;
                max_tokens: number;
                top_p: number;
            };
            tools?: ""[];
            prompt?: string | null;
            prompt_version?: number | null;
            sub_agents?: string[];
        };
        /** StoreMcpInstructionVersionRequest */
        StoreMcpInstructionVersionRequest: {
            content: string;
            publish?: boolean;
        };
        /** StorePromptRequest */
        StorePromptRequest: {
            name: string;
            slug: string;
            description?: string | null;
            content: string;
            publish?: boolean;
        };
        /** StorePromptVersionRequest */
        StorePromptVersionRequest: {
            content: string;
            publish?: boolean;
        };
        /** StoreToolDescriptionVersionRequest */
        StoreToolDescriptionVersionRequest: {
            content: string;
            publish?: boolean;
        };
        /** ToolDescriptionResource */
        ToolDescriptionResource: {
            tool: string;
            published_version: number;
            published_content: string;
            created_at: string | null;
            updated_at: string | null;
        };
        /** ToolDescriptionVersionResource */
        ToolDescriptionVersionResource: {
            version: number;
            content: string;
            created_at: string | null;
        };
        /** ToolResource */
        ToolResource: {
            name: string;
            description: string;
            schema: string;
        };
        /** UpdateAgentRequest */
        UpdateAgentRequest: {
            name?: string;
            description?: string | null;
            provider?: string | null;
            model?: string | null;
            settings?: {
                temperature: number;
                max_steps: number;
                max_tokens: number;
                top_p: number;
            };
            tools?: ""[];
            prompt?: string | null;
            prompt_version?: number | null;
            sub_agents?: string[];
        };
        /** UpdatePromptRequest */
        UpdatePromptRequest: {
            name?: string;
            description?: string | null;
        };
    };
    responses: {
        /** @description Validation error */
        ValidationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Errors overview. */
                    message: string;
                    /** @description A detailed description of each field that failed validation. */
                    errors: {
                        [key: string]: string[];
                    };
                };
            };
        };
        /** @description Not found */
        ModelNotFoundException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "cortex.agents.index": {
        parameters: {
            query?: {
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `AgentResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AgentResource"][];
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "cortex.agents.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreAgentRequest"];
            };
        };
        responses: {
            /** @description `AgentResource` */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AgentResource"];
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "cortex.agents.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The agent slug */
                agent: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `AgentResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AgentResource"];
                    };
                };
            };
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "cortex.agents.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The agent slug */
                agent: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "cortex.agents.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The agent slug */
                agent: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateAgentRequest"];
            };
        };
        responses: {
            /** @description `AgentResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AgentResource"];
                    };
                };
            };
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "cortex.agents.run": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The agent slug */
                agent: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunAgentRequest"];
            };
        };
        responses: {
            /** @description `AgentRunResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["AgentRunResource"];
                    };
                };
            };
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "cortex.servers.instructions.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                server: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `McpInstructionResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["McpInstructionResource"];
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "cortex.servers.instructions.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                server: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "cortex.servers.instructions.versions.index": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                server: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `McpInstructionVersionResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["McpInstructionVersionResource"][];
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "cortex.servers.instructions.versions.store": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                server: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreMcpInstructionVersionRequest"];
            };
        };
        responses: {
            /** @description `McpInstructionVersionResource` */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["McpInstructionVersionResource"];
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "cortex.servers.instructions.versions.publish": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                server: string;
                version: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `McpInstructionResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["McpInstructionResource"];
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "cortex.servers.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `McpServerResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["McpServerResource"][];
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "cortex.prompts.index": {
        parameters: {
            query?: {
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `PromptResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PromptResource"][];
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "cortex.prompts.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StorePromptRequest"];
            };
        };
        responses: {
            /** @description `PromptResource` */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PromptResource"];
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "cortex.prompts.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The prompt slug */
                prompt: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `PromptResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PromptResource"];
                    };
                };
            };
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "cortex.prompts.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The prompt slug */
                prompt: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "cortex.prompts.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The prompt slug */
                prompt: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdatePromptRequest"];
            };
        };
        responses: {
            /** @description `PromptResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PromptResource"];
                    };
                };
            };
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "cortex.prompts.versions.index": {
        parameters: {
            query?: {
                page?: number;
            };
            header?: never;
            path: {
                /** @description The prompt slug */
                prompt: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `PromptVersionResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PromptVersionResource"][];
                    };
                };
            };
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "cortex.prompts.versions.store": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The prompt slug */
                prompt: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StorePromptVersionRequest"];
            };
        };
        responses: {
            /** @description `PromptVersionResource` */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PromptVersionResource"];
                    };
                };
            };
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "cortex.prompts.versions.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The prompt slug */
                prompt: string;
                version: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `PromptVersionResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PromptVersionResource"];
                    };
                };
            };
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "cortex.prompts.versions.publish": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The prompt slug */
                prompt: string;
                version: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `PromptResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["PromptResource"];
                    };
                };
            };
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "cortex.providers.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: string;
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "cortex.tools.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `ToolResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ToolResource"][];
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "cortex.tools.description.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tool: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `ToolDescriptionResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ToolDescriptionResource"];
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "cortex.tools.description.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tool: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "cortex.tools.description.versions.index": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tool: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of `ToolDescriptionVersionResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ToolDescriptionVersionResource"][];
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "cortex.tools.description.versions.store": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tool: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreToolDescriptionVersionRequest"];
            };
        };
        responses: {
            /** @description `ToolDescriptionVersionResource` */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ToolDescriptionVersionResource"];
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "cortex.tools.description.versions.publish": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tool: string;
                version: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `ToolDescriptionResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ToolDescriptionResource"];
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
}
